"""Session attributes"""
DEPARTURE_CITY = "DEPARTURE_CITY"
DESTINATION_CITY = "DESTINATION_CITY"
DEPARTURE_DATE = "DEPARTURE_DATE"
DEPARTURE_TIME = "DEPARTURE_TIME"

RETURN_TICKET = "RETURN_TICKET"
DEPARTURE_DATE_RETURN = "DEPARTURE_DATE_RETURN"
DEPARTURE_TIME_RETURN = "DEPARTURE_TIME_RETURN"

PASSENGERS_NO = "PASSENGERS_NO"
SEAT_RESERVATION = "SEAT_RESERVATION"
INSURANCE = "INSURANCE"
CONFIRM_BOOKING = "CONFIRM_BOOKING"

"""INNER LOGIC FLAGS"""
SHORTEN_FLIGHTS_LIST = "SHORTEN_FLIGHTS_LIST"
ALTERNATIVE_FLIGHTS = "ALTERNATIVE_FLIGHTS"

"""CONSTANTS"""
SEAT_PRICE = 10
INSURANCE_PRICE = 15

FLIGHT_MIN_PRICE = 40
FLIGHT_MAX_PRICE = 400

LISTED_FLIGHTS_NUMBER = 3

TESTS = 1 # if true shows variables info in terminal



