"""This module does blah blah."""
DEPARTURE_DATE = "DEPARTURE_DATE"
DEPARTURE_CITY = "DEPARTURE_CITY"
DESTINATION_CITY = "DESTINATION_CITY"
PASSENGERS_NO = "PASSENGERS_NO"
SEAT_RESERVATION = "SEAT_RESERVATION"
INSURANCE = "INSURANCE"
CONFIRM_BOOKING = "CONFIRM_BOOKING"


SEAT_PRICE = 10
INSURANCE_PRICE = 15

FLIGHT_MIN_PRICE = 40
FLIGHT_MAX_PRICE = 400